spring:
  datasource:
    url: jdbc:postgres://localhost:5432/usermanager
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
#  mail:
#    password: fiqv ybrp znse tomu
#    username: confirmation.usermanager@gmail.com
#    host: smtp.gmail.com
#    port: 587
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  error:
    include-message: always


app:
  mail:
    host: smtp.gmail.com
    port: 587
    username: confirmation.usermanager@gmail.com
    password: fiqv ybrp znse tomu
    protocol-key: mail.transport.protocol
    protocol-value: smtp
    smtp-key: mail.smtp.auth
    smtp-value: true
    starttls-key: mail.smtp.starttls.enable
    starttls-value: true

jws:
  sharedKey: bdc6e4de-a1b9-49d4-bdec-39c2f0c62261

